apiVersion: v1
kind: Service
metadata:
  name: nickveenhofbe
  labels:
    site: nickveenhofbe
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP
  selector:
    service: nickveenhofbe