apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-shared1-server
spec:
  replicas: 1
  selector:
    role: nfs-shared1-server
  template:
    metadata:
      labels:
        role: nfs-shared1-server
    spec:
      containers:
      - name: nfs-shared1-server
        image: gcr.io/google_containers/volume-nfs:0.8
        resources:
            limits:
              cpu: 0.01
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-shared1-200gb
      volumes:
        - name: nfs-shared1-200gb
          persistentVolumeClaim:
            claimName: nfs-shared1-200gb